apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: kiali-operator
  namespace: flux-system
spec:
  interval: 1h
  chart:
    spec:
      chart: kiali-operator
      version: "2.1.0"
      sourceRef:
        kind: HelmRepository
        name: kiali
        namespace: flux-system
  targetNamespace: kiali-operator
  install:
    createNamespace: true
  upgrade:
    createNamespace: true
---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: prometheus
  namespace: flux-system
spec:
  interval: 1h
  chart:
    spec:
      chart: prometheus
      version: "25.8.0"
      sourceRef:
        kind: HelmRepository
        name: prometheus-community
        namespace: flux-system
  targetNamespace: monitoring-online-boutique
  install:
    createNamespace: true
  upgrade:
    createNamespace: true
---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: grafana
  namespace: flux-system
spec:
  interval: 1h
  chart:
    spec:
      chart: grafana
      version: "7.0.0"
      sourceRef:
        kind: HelmRepository
        name: grafana
        namespace: flux-system
  targetNamespace: monitoring-online-boutique
  install:
    createNamespace: true
  upgrade:
    createNamespace: true
